#!/bin/bash
set -eo pipefail

HOST=$1
ORG=${2:-"pivotal"}
SPACE=${3:-"integration"}

cf api api.$HOST --skip-ssl-validation
cf_password=${CF_PASSWORD:-"admin"}

cf login -u admin -p $cf_password -o $ORG -s $SPACE || true
cf create-org $ORG
cf target -o $ORG

cf create-space $SPACE -o $ORG
cf target -s $SPACE -o $ORG

cf login -u admin -p $cf_password -o $ORG -s $SPACE
